# Modelling Radioactive Decay Using Python 3
### Written by Inigo Val

In this lab, we will be using the programming language Python 3 to create a model simulating the radioactive decay of a number of particles over time.

In order to complete this lab you should be comfortable with exponential decay and half lives. You must have come across vectors and matrices before (although no in depth knowledge is required). __No previous programming knowledge is required__. This excercise aims to be self contained so you should be able to jump right in without any prior reading. You are however encouraged to use google as you go through the excercises to help you understand/find syntax. 

We will mainly be using the [NumPy](http://www.numpy.org/) _package_ which provides a powerful framework for numerical computations in Python.

All excercises _without_ asterisks should be completed; tasks _with_ asterisks are extensions and are usually more exploratory. These can be omitted until you have finished all other tasks.

## Beginner Programming in Python

First we need to tell the computer to load NumPy so that we can use it in our code.

In order to run the import code (or any code in a given _cell_), select the cell by clicking on it. Hold shift and press enter. __If you get an error, you haven't installed NumPy correctly.__

The second part of the import ('as np') simply saves us time by allowing us to type 'np' instead of 'numpy' every time we wish to use something from the NumPy package.

In [7]:
# This is a comment. It is NOT executed by the computer and is there to annotate the code, making it easier to read.
# Commenting is encouraged and will help you and other people understand your code. Comments are denoted by beginning
# the line with a hash (#).

First we need to tell the computer to load NumPy so that we can use it in our code.

In order to run the import code (or any code in a given _cell_), select the cell by clicking on it. Hold shift and press enter. If you get an error, you haven't installed NumPy correctly.

The second part of the import ('as np') simply saves us time by allowing us to type 'np' instead of 'numpy' every time we wish to use something from the NumPy package.

In [8]:
import numpy as np

The print function is a fundamental part of Python and it prints an object to the console.

In [9]:
print(3)

3


You can also print multiple things on the same line

In [10]:
print(3, 5, 6, 7)

3 5 6 7


Words need to be given to the print function as a ```string``` by wrapping them in apostrophes like this:

In [11]:
print('this is a string')

this is a string


Print the following things:

* supersymmetry
* quarks leptons 4523

In [12]:
print('supersymmetry')
print('quarks', 'leptons', 11235813)

supersymmetry
quarks leptons 11235813


Basic mathematical operations do not require NumPy. A table of symbols follows: <br/>

multiply         ```*```   <br/>
divide           ```/```   <br/>
add              ```+```    <br/>
subtract         ```-```    <br/>
to the power of  ```**``` <br/>

Brackets work as normal.

Use this information to print :
* Square root of 2
* Radius of a circle of perimeter 5 (use any reasonable estimate for pi)
* Sum of the first 5 numbers in the Fibonacci sequence

In [13]:
print(2**0.5)
print(5/(2*3.14))
print(1+1+2+3+5)

1.4142135623730951
0.7961783439490445
12


## Using NumPy

Single numbers are not hugely useful. Numpy uses vectors and matrices to carry out computations on lots of numbers at once. A single number is simply a 1x1 vector. In NumPy, all 3 of these are grouped together and called _arrays_. The words array/vector/matrix will all be used interchangeably depending on context to aid your understanding.

### Indexing

The simplest way of creating an array is by just typing it out. You can use any _element_ of the vector by using the _index_ of the element. __Indices always start at 0 not 1!__.

In [25]:
# Creating a 3D vector 
vector = np.array([10, 2, 5])

# Printing the 2nd element of the vector
index = 0
element = vector[index] # REMEMBER TO USE SQUARE BRACKETS!
print(element) # print the second element int the vector (2)

2
10


Create a vector with the first 7 numbers of the Fibonacci sequence. Using indexing and mathematical operations, print the following values:

* 8 in two different ways
* 26
* 40
* 0.6666666666666666

In [28]:
fibonacci = np.array([1,1,2,3,5,8,13])

print(fibonacci[5])
print(fibonacci[3] + fibonacci[4])
print(fibonacci[6]*fibonacci[2])
print(fibonacci[5]*fibonacci[4])
print(fibonacci[2]/fibonacci[3])

8
8
26
40
0.6666666666666666


You can also reassign the value of an element by using indexing:

In [46]:
print(vector[1])
vector[1] = 100
print(vector[1])

2
100


Reassign the last element of the ```fibonacci``` vector to 50 and then print it to make sure you've done it correctly.

In [47]:
fibonacci[6] = 50
print(fibonacci[6])

50


### Generating Arrays

There are many, many functions in NumPy so you can (mostly) avoid manually typing out arrays. For example the arange function creates an ascending vector up to the specified __index__ (remember this starts at 0!).

In [37]:
vector_2 = np.arange(10)
print(vector_2)

[0 1 2 3 4 5 6 7 8 9]


np.random.rand(n,m) is another very useful function. It creates an array of numbers randomised between 0 and 1. The array is size nxm (so if m>1 it will be a matrix). If you only want a vector you don't have to specify the second dimension as being 1.

In [38]:
print(np.random.rand(5))

[0.31261363 0.61339985 0.96407195 0.73106233 0.59043804]


Arrays are, by default, multiplied together __element-wise__ unlike in conventional mathematics. Every number in the 1st matrix is multiplied by the number occupying the same position in the 2nd matrix. Division works in the same way. This means the shape of both arrays _must_ be the same. You can use the same operators as usual (* and /).

Numpy also has functions that can do various other operations (dot product, cross product, regular matrix multiplication etc.) but we will not require these.

* Create a random matrix with 3 columns and 5 rows
* Multiply it by another random matrix (with different values) and print the result
* What is the maximum possible value any element in the resulting matrix can have and why? Is this a likely result?
* *Calculate the likelihood of this occuring in the given case. You may give your answer in indice form.

In [39]:
matrix_1 = np.random.rand(3,5)
matrix_2 = np.random.rand(3,5)
matrix_3 = matrix_2*matrix_1

print(matrix_3)

[[0.00176276 0.0743811  0.03292264 0.35115747 0.30215872]
 [0.42491271 0.36768336 0.83561993 0.41120898 0.17713738]
 [0.67969616 0.15028335 0.27731488 0.30761631 0.07699957]]


Maximum value any element can have is 1, in the case that the random number generated both times in that element is 1. This is very unlikely.

$$ \frac{1}{10^8} \times \frac{1}{10^8} \times 16 = 1.6 \times 10^{-15}$$

* Create an ascending vector of length 9 and a vector of random numbers length 6.

* Try to add the two matrices together. Why does python throw an error?

* Change one of the vectors so that the addition can work.

In [29]:
vector_1 = np.arange(6)
vector_2 = np.random.rand(6)

vector_1 + vector_2

array([0.69417903, 1.48454489, 2.11281415, 3.86154982, 4.62706508,
       5.23727453])

## Further Programming in Python

### If Statements

'If' statements in Python are similar to how we use them in natural language. The basic framework goes as follows:

if X is a true statement then do Y

However, when we are coding, instead of using words we use symbols: <br/>
equal to       ```==``` <br/>
not equal to   ```!=``` <br/>
less than      ```<``` <br/>
more than      ```>``` <br/>

These symboles evaluate the given statement and return ```True``` or ```False```.

We also need to include a colon after our if statement and indent the next line, so that the program knows where the if statement begins and ends.

In [40]:
print(5 < 3)
print(5==5) # NOTE THE DOUBLE EQUALS SIGN!

if 5>0:
    print('5 is greater than 0')

False
True
5 is greater than 0


* Assign a number to a variable ```n```.

* Write an if statement that prints ```yes``` if the square of n is greater than 16. Run this a few times, changing the value of n and check that the program works as you expect

In [30]:
n = 1

if n**2 > 16:
    print('yes')

* Write an if statement that has a 50% chance of printing the square of ```n```. _Hint: Use a randomly generated number in your if statement_.

* Run this multiple times to check it works.

In [45]:
if np.random.rand(1) < 0.5:
    print(n**2)

### For Loops

#### Basic Looping

The last key ingredient of programming in any language is the for loop. It allows us to run a segment of code an arbitrary number of times (most of the time on different inputs). The power of this iterative way of approaching a problem is the often the reason we turn to a computer in the first place. The framework is as follows:

for x in X
do y to x

where x (scalar) is an element of X (a vector) and y is some action on x

This will be much clearer with an example. In the example below, the ```print``` function is the action y.

In [41]:
X = np.arange(5)
print(X)

rand_vector = np.random.rand(5)
print(rand_vector)

for x in X:
    print(x)
    print(rand_vector[x])

[0 1 2 3 4]
[0.99207417 0.97620005 0.29564798 0.65123405 0.0314773 ]
0
0.9920741650961162
1
0.976200051748395
2
0.2956479831950566
3
0.6512340532561474
4
0.03147729509109387


* Create a vector of ascending numbers (as above). Use a for loop to print the square and square root of each of the numbers.


In [50]:
X = np.arange(5)

for x in X:
    print(x**2, x**0.5)

1
2
3
4


* Create a vector of random numbers (between 0 and 1). Use an ```if``` statement _inside_ a ```for``` loop to iterate through the vector and print any numbers over 0.5.

In [53]:
X = np.random.rand(5)

for x in X:
    if x > 0.5:
        print(x)

0.9508364787476099
0.8710506792581874
0.5315700968480959
0.6027529283857919


* Create a random vector of length 5. Use a for loop to replace every element in the vector with a 1 if the element is above 0.5 and 0 if the element is below 0.5. _Hint: begin the for loop with_ ```for i in np.arange(4):``` _and use ```i``` as an index for random vector.

In [55]:
X = np.random.rand(5)

for i in np.arange(4):
    # Replace values higher than 0.5
    if X[i] > 0.5:
        X[i] = 1
    
    # Replace values lower than 0.5
    if X[i] < 0.5:
        X[i] = 0

#### Breaking a Loop

In some cases, we want to break the ```for``` loop before it has completed all of its loops. To do this we can use the ```break``` statement. ```break``` is most commonly wrapped in an if statement.

Have a look at the example below and see if you can edit it so that it breaks after the 4th loop.

In [42]:
for i in np.arange(20):
    print(i, i**2)
    if i == 10:
        break

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100


* Create a random vector of length 15.

* Write a ```for``` loop which iterates through the vector and stops when it reaches a number greater than 0.8.

* Print the number it stops at.

* Run the program and see if it works.

* Add a new variable ```n``` assigned value 0 before your loop starts.

* Add 1 to n at the __end__ of every iteration.

* Print ```n``` next to your number when the loop breaks. This tells you the index where your loop stopped.

* Run a few times to make sure it's working. Use the value of ```n``` as an index for your random vector and verify that you get the same number. Why is it important that ```n``` increases at the end of the iteration and not the start?

In [78]:
X = np.random.rand(5)
n = 0

for x in X:
    
    if x>0.8:
        print(n, x)
        break
        
    n+=1 

1 0.815250317549785


In [80]:
print(X[n])

0.815250317549785


If ```n``` increased at the start of every iteration, it would be 1 ahead of the index.

## Physics Recap

Now we're ready for the fun bit! Let's apply the concepts we've learned to model some real Physics.

Before we continue, let's make sure we remember the necessary Physics. You will need a pencil/pen and paper for this bit.

* If we have N particles with each particle having a probability per second of decaying p, what is the rate of change of N (dN/dt)? 
* Why can't we simply integrate this equation (with respect to t)?
* Solve this differential equation to find N as a function of time. (Just look up the answer at the end of this document if you haven't studied any differential equations yet).
* Define the _half life_ of a radioactive sample.
* Derive the half life &lambda; using the equation for N found earlier.

There are answers and hints at the end of this document, but you should attempt this without them first.

## A Single Particle System

Using the tools we have learned, we can now model a single radioactive particle. First we will attempt to model a single particle with _p_ = 0.1 as it evolves through time.

Follow the instructions below to model the particle over a single second.

* Create a 1x1 array labelled ```particle``` with a single entry (scalar) of 0.

* Generate a random number between 0 and 1.

* If the number is greater than _p_, add 1 to ```particle```.

* If the value of ```particle``` is 1 then it has decayed, if it is 0 then it has not decayed.

In [43]:
particle = np.array([0]) # create array with a single zero representing a particle in state 0
p = 0.1 # probability of decay

if np.random.rand() < p: # if roll is greater than probability
    particle  = particle + 1 # particle 'decays' to state 1

We can then simulate the passage of time by using a for loop, with each loop representing a second passing for the particle. During each loop, the particle will thus have a probability _p_ of decaying.

Follow the the instructions below to extend our model so that it allows for the passage of time.

* Reassign ```particle``` to 0 in case it decayed when you ran the earlier ```if``` statement.

* Set the probability of decay at 0.2.

* Wrap your ```if``` statement inside a ```for``` loop with n=30 iterations. _Hint: use the ```np.arange()``` function._

* At the end of each loop, print the number of loops completed and the ```particle``` array _on separate lines_.

* Run your program and see what happens. Why does the computation happen so fast?

* Add in ```time.sleep(1)``` at the end of your for loop so that the computer pauses for 1 second before executing the next loop.

* Add ```clear_output(wait=True)``` at the end of your loop. This will clear the output every iteration and is only aesthetic to avoid a long list of outputs.

* Run your program again. If we assume the particle we are modelling can only decay once, does it make physical sense for ```particle``` to have a value greater than one?

* Use an if statement to terminate the ```for``` loop if the particle is already in state 1.

* Run your program a few times, trying different values for ```p``` and n (number of iterations). Make sure that you aren't getting any errors and it behaves as you expect: 
    * ```for``` loop terminates when the particle decays
    * Generally takes more (fewer) steps to decay when you decrease (increase) p
    * End with a decayed particle in state 1 (or the loop has gotten to 

In [44]:
# this is just a function to clear the output
from IPython.display import clear_output

# package which allows us to delay the for loop (otherwise the loop would be executed almost instantaneously)
import time

In [45]:
particle = np.array([0]) # single particle in state 0
p = 0.1 # probability of decay
n = 30 # number of iterations

for i in np.arange(n): # 30 time steps
    
    # 0.1 probability of executing the decay
    if np.random.rand() < p:
        particle = particle + 1    
    
    # print step number and state of particle
    print('step', i)
    print(particle)
    
    # pause for 1 second
    time.sleep(1)
    
    # if the particle has decayed to state 1, stop the loop
    if particle == 1:
        break
    
    # clear the output
    clear_output(wait=True)

step 11
[1]


## Multiple Decay, Multi Particle System

Now we are ready to add some more complicated elements to our model. First we will simulate a single particle decaying multiple times instead of one. Can you guess how we might represent this in our mathematical model before reading the next bit? Try and think about it before reading on. _Hint: state 0 represents and undecayed particle and state 1 represents the particle after 1 decay._

To represent a multi particle decay we will use the number 2 represent the next decayed state:

* How many decays are there in this new system?

* Copy over all the code from your previous model with only one decay into the following cell

* Since we have two decays, we will need 2 probabilities (one for each decay). Replace the single probability ```p``` with ```p1``` and ```p2```; you may choose any reasonable values you wish.

* Create a second ```if``` statement to represent the second decay of the particle. __Be careful__ - you will need an if statement inside an if statement to make sure the second decay can only happen if the particle is already in state 1.

* Change the if statement that breaks the for loop to allow for state 2 to exist.

In [46]:
particle = np.array([0]) # single particle in state 0

# probabilities of decay
p1 = 0.1
p2 = 0.2

n = 30 # number of iterations

for i in np.arange(n): # 30 time steps
    
    # 0.1 probability of executing the decay
    if np.random.rand() < p1:
        particle = particle + 1
    
    # second decay
    if particle == 1: # only allow decay if already in state 1
        if np.random.rand() < p2:
            particle = particle + 1
    
    # print step number and state of particle
    print('step', i)
    print(particle)
    
    # pause for 1 second
    time.sleep(1)
    
    # if the particle has decayed to state 1, stop the loop
    if particle == 2:
        break
    
    # clear the output
    clear_output(wait=True)

step 5
[2]
