# Modelling Radioactive Decay Using Python 3

In this lab, we will be using the programming language Python 3 to create a model simulating the radioactive decay of a number of particles over time.

In order to complete this lab you should be comfortable with exponential decay and half lives. You must have come across vectors and matrices before (although no in depth knowledge is required). __No previous programming knowledge is required__. This excercise aims to be self contained so you should be able to jump right in without any prior reading. You are however encouraged to use google as you go through the excercises to help you understand/find syntax. 

We will mainly be using the [NumPy](http://www.numpy.org/) _package_ which provides a powerful framework for numerical computations in Python. We will also use the MatPlotLib and seaborn to visualise our results.

All excercises _without_ asterisks should be completed; tasks _with_ asterisks are extensiosn and are usually more exploratory.

## Beginner Programming in Python

Before getting started, it's necessary to install the necessary software onto your computer. It is different for every operating system (Linux/Windows/Mac) so a guide is not provided here. You should use Google to install Python3, Numpy . Anaconda is a convenient way of installing all the necessary packages at once, but it does take up a lot of memory with packages we won't be using.

In [1]:
# This is a comment. It is NOT executed by the computer and is there to annotate the code, making it easier to read.
# Commenting is encouraged and will help you and other people understand your code. Comments are denoted by beginning
# the line with a hash (#).

First we need to tell the computer to load NumPy so that we can use it in our code.

In order to run the import code (or any code in a given _cell_), select the cell by clicking on it. Hold shift and press enter. If you get an error, you haven't installed NumPy correctly.

The second part of the import ('as np') simply saves us time by allowing us to type 'np' instead of 'numpy' every time we wish to use something from the NumPy package.

In [2]:
import numpy as np

The print function is a fundamental part of Python and it prints an object to the console.

In [3]:
print(3)

3


You can also print multiple things on the same line

In [4]:
print(3, 5, 6, 7)

3 5 6 7


Basic mathematical operations do not require Python. A table of symbols follows: <br/>

multiply         ```*```   <br/>
divide           ```/```   <br/>
add              ```+```    <br/>
subtract         ```-```    <br/>
to the power of  ```**``` <br/>

Brackets work as normal.

Use this information to print :
* Square root of 2
* Radius of a circle of perimeter 5 (use any reasonable estimate for pi)

In [5]:
print(2**0.5)
print(5/(2*3.14))

1.4142135623730951
0.7961783439490445


## Using NumPy

Single numbers are not hugely useful. Numpy uses vectors and matrices to carry out computations on lots of numbers at once. A single number is simply a 1x1 vector. In NumPy, all 3 of these are grouped together and called _arrays_. The words array/vector/matrix will all be used interchangeably depending on context to aid your understanding.

The simplest way of creating an array is by just typing it out. You can use any _element_ of the vector by using the _index_ of the element. __Indices always start at 0 not 1!__.

In [6]:
# Creating a 3D vector 
vector = np.array([10, 2, 5])

# Printing the 2nd element of the vector
print(vector[1])

2


There are many, many functions in NumPy so you can (mostly) avoid manually typing out arrays. For example the arange function creates an ascending vector up to the specified __index__ (remember this starts at 0!).

In [7]:
vector_2 = np.arange(10)
print(vector_2)

[0 1 2 3 4 5 6 7 8 9]


np.random.rand(n,m) is another very useful function. It creates an array of numbers randomised between 0 and 1. The array is size nxm (so if m>1 it will be a matrix). If you only want a vector you don't have to specify the second dimension as being 1.

In [8]:
print(np.random.rand(5))

[0.14699269 0.29115427 0.66432027 0.63628752 0.09372243]


Arrays are, by default, multiplied together __element-wise__ unlike in conventional mathematics. Every number in the 1st matrix is multiplied by the number occupying the same position in the 2nd matrix. Division works in the same way. This means the shape of both arrays _must_ be the same. You can use the same operators as usual (* and /).

Numpy also has functions that can do various other operations (dot product, cross product, regular matrix multiplication etc.) but we will not require these.

* Create a random matrix with 3 columns and 5 rows
* Multiply it by another random matrix (with different values) and print the result
* What is the maximum possible value any element in the resulting matrix can have and why? Is this a likely result?
* *Calculate the likelihood of this occuring in the given case.

In [9]:
matrix_1 = np.random.rand(3,5)
matrix_2 = np.random.rand(3,5)
matrix_3 = matrix_2*matrix_1

print(matrix_3)

[[0.11167424 0.00449    0.00742437 0.02215071 0.20566855]
 [0.59655489 0.02111416 0.50299328 0.21469003 0.20958718]
 [0.01128382 0.79748169 0.17624494 0.04648514 0.37747841]]


## Further Programming in Python

### If Statements

'If' statements in Python are similar to how we use them in natural language. The basic framework goes as follows:

if X is a true statement then do Y

However, when we are coding, instead of using words we use symbols: <br/>
equal to       ```==``` <br/>
not equal to   ```!=``` <br/>
less than      ```<``` <br/>
more than      ```>``` <br/>

These symboles evaluate the given statement and return ```True``` or ```False```.

We also need to include a colon after our if statement and indent the next line, so that the program knows where the if statement begins and ends.

In [10]:
print(5 < 3)
print(5==5)

if 5>0:
    print('5 is greater than 0')

False
True
5 is greater than 0


### For Loops

#### Basic Looping

The last key ingredient of programming in any language is the for loop. It allows us to run a segment of code an arbitrary number of times (most of the time on different inputs). The power of this iterative way of approaching a problem is the often the reason we turn to a computer in the first place. The framework is as follows:

for x in X
do y to x

where x (scalar) is an element of X (a vector) and y is some action on x

This will be much clearer with an example. In the example below, the ```print``` function is the action y.

In [11]:
X = np.arange(5)
print(X)

rand_vector = np.random.rand(5)
print(rand_vector)

for x in X:
    print(x)
    print(rand_vector[x])

[0 1 2 3 4]
[0.55340851 0.52590419 0.07705441 0.76558274 0.5057577 ]
0
0.5534085062458374
1
0.5259041860278156
2
0.07705440546890274
3
0.7655827425937881
4
0.5057576962268865


##### Exercises:

* Create a vector of ascending numbers (as above). Use a for loop to print the square and square root of each of the numbers.

* Manually create a vector of length 5 with any values you choose. Use a for loop to add 10 to every element in the vector. _Hint: begin the for loop with_ ```for i in np.arange(4):``` _and use ```i``` as an index for the vector you've manually written out_.

* Create a vector of random numbers (between 0 and 1). Use an ```if``` statement _inside_ a ```for``` loop to iterate through the vector and print any numbers over 0.5.

* 

#### Breaking

In some cases, we want to break the ```for``` loop before it has completed all of its loops. To do this we can use the ```break``` statement. ```break``` is most commonly wrapped in an if statement.

Have a look at the example below and see if you can edit it so that it breaks after the 4th loop.

In [12]:
for i in np.arange(20):
    print(i, i**2)
    if i == 10:
        break

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100


## Physics Recap

Before we continue, let's make sure we remember the Physics necessary to model radioactive decay. You will need a pencil/pen and paper for this bit.

* If we have N particles with each particle having a probability per second of decaying p, what is the rate of change of N (dN/dt)? 
* Why can't we simply integrate this equation (with respect to t)?
* Solve this differential equation to find N as a function of time. (Just look up the answer at the end of this document if you haven't studied any differential equations yet).
* Define the _half life_ of a radioactive sample.
* Derive the half life &lambda; using the equation for N found earlier.

There are answers and hints at the end of this document, but you should attempt this without them first.

## A Single Particle System

Using the tools we have learned, we can now model a single radioactive particle. First we will attempt to model a single particle with _p_ = 0.1 as it evolves through time.

Follow the instructions below to model the particle over a single second.

* Create a 1x1 array labelled ```particle``` with a single entry (scalar) of 0.

* Generate a random number between 0 and 1.

* If the number is greater than _p_, add 1 to ```particle```.

* If the value of ```particle``` is 1 then it has decayed, if it is 0 then it has not decayed.

In [13]:
particle = np.array([0])
p = 0.1

if np.random.rand() > p:
    particle  = particle + 1

We can then simulate the passage of time by using a for loop, with each loop representing a second passing for the particle. During each loop, the particle will thus have a probability _p_ of decaying.

Follow the the instructions below to extend our model so that it allows for the passage of time.

* Reassign ```particle``` to 0 in case it decayed when you ran the earlier ```if``` statement.

* Wrap your ```if``` statement inside a ```for``` loop with 30 iterations. _Hint: use the ```np.arange()``` function._

* At the end of each loop, print the number of loops completed and the value of ```particle``` _on the same line_.

* Run your program and see what happens. If we assume the particle we are modelling can only decay once, does it make physical sense for ```particle``` to have a value greater than one? What might this be able to 

* 

In [14]:
import seaborn as sns

particle = np.array([0])
p = 0.1

for i in np.arange(30):
    if np.random.rand() > p:
        particle = particle + 1
 
    ax = sns.heatmap(particle)
    
    if particle == 1:
        break
        

ModuleNotFoundError: No module named 'seaborn'