# Modelling Radioactive Decay Using Python 3

In this lab, we will be using the programming language Python 3 to create a model simulating the radioactive decay of a number of particles over time.

In order to complete this lab you should be comfortable with exponential decay and half lives. You must have come across vectors and matrices before (although no in depth knowledge is required). __No previous programming knowledge is required__. This excercise aims to be self contained so you should be able to jump right in without any prior reading. You are however encouraged to use google as you go through the excercises to help you understand/find syntax. 

We will mainly be using the [NumPy](http://www.numpy.org/) _package_ which provides a powerful framework for numerical computations in Python. We will also use the MatPlotLib and seaborn to visualise our results.

All excercises _without_ asterisks should be completed; tasks _with_ asterisks are extensiosn and are usually more exploratory.

## Beginner Programming in Python

Before getting started, it's necessary to install the necessary software onto your computer. It is different for every operating system (Linux/Windows/Mac) so a guide is not provided here. You should use Google to install Python3, Numpy . Anaconda is a convenient way of installing all the necessary packages at once, but it does take up a lot of memory with packages we won't be using.

In [22]:
# This is a comment. It is NOT executed by the computer and is there to annotate the code, making it easier to read.
# Commenting is encouraged and will help you and other people understand your code. Comments are denoted by beginning
# the line with a hash (#).

First we need to tell the computer to load NumPy so that we can use it in our code.

In order to run the import command (or any command in a given _cell_), select the cell by clicking on it. Hold shift and press enter. If you get an error, you haven't installed NumPy correctly.

The second part of the import ('as np') simply saves us time by allowing us to type 'np' instead of 'numpy' every time we wish to use something from the NumPy package.

In [11]:
import numpy as np

The print function is a fundamental part of Python and it prints an object to the console.

In [8]:
print(3)

3


Basic mathematical operations do not require Python. A table of symbols follows: <br/>

multiply         *   <br/>
divide           /   <br/>
add              +    <br/>
subtract         -    <br/>
to the power of  ** <br/>

Brackets work as normal.

Use this information to print :
* Square root of 2
* Radius of a circle of perimeter 5 (use any reasonable estimate for pi)

In [10]:
print(2**0.5)
print(5/(2*3.14))

1.4142135623730951
0.7961783439490445


## Using NumPy

Single numbers are not hugely useful. Numpy uses vectors and matrices to carry out computations on lots of numbers at once. A single number is simply a 1x1 vector. In NumPy, all 3 of these are grouped together and called _arrays_. The words array/vector/matrix will all be used interchangeably depending on context to aid your understanding.

The simplest way of creating an array is by just typing it out. You can use any _element_ of the vector by using the _index_ of the element. __Indices always start at 0 not 1!__.

In [15]:
# Creating a 3D vector 
vector = np.array([10, 2, 5])

# Printing the 2nd element of the vector
print(vector[1])

2


There are many, many functions in NumPy so you can (mostly) avoid manually typing out arrays. For example the arange function creates an ascending vector up to the specified __index__ (remember this starts at 0!).

In [17]:
vector_2 = np.arange(10)
print(vector_2)

[0 1 2 3 4 5 6 7 8 9]


np.random.rand(n,m) is another very useful function. It creates an array of numbers randomised between 0 and 1. The array is size nxm (so if m>1 it will be a matrix). If you only want a vector you don't have to specify the second dimension as being 1.

In [19]:
print(np.random.rand(5))

[0.46236874 0.46605345 0.27103728 0.52936335 0.25026887]


Arrays are, by default, multiplied together __element-wise__ unlike in conventional mathematics. Every number in the 1st matrix is multiplied by the number occupying the same position in the 2nd matrix. Division works in the same way. This means the shape of both arrays _must_ be the same. You can use the same operators as usual (* and /).

Numpy also has functions that can do various other operations (dot product, cross product, regular matrix multiplication etc.) but we will not require these.

* Create a random matrix with 3 columns and 5 rows
* Multiply it by another random matrix (with different values) and print the result
* What is the maximum possible value any element in the resulting matrix can have and why? Is this a likely result?
* *Calculate the likelihood of this occuring in the given case.

In [20]:
matrix_1 = np.random.rand(3,5)
matrix_2 = np.random.rand(3,5)
matrix_3 = matrix_2*matrix_1

print(matrix_3)

[[0.06898982 0.43592189 0.1722936  0.1649764  0.0844597 ]
 [0.12058178 0.19156065 0.39409779 0.08569823 0.23800907]
 [0.08237019 0.44927879 0.15808222 0.01611441 0.41985579]]


## Further Programming in Python

### If Statements

'If' statements in Python are similar to how we use them in natural language. The basic framework goes as follows:

if X is a true statement then do Y

However, when we are coding, instead of using words we use symbols: <br/>
equal to       == <br/>
not equal to   != <br/>
less than      < <br/>
more than      > <br/>

These symboles evaluate the given statement and return ```True``` or ```False```.

We also need to include a colon after our if statement and indent the next line, so that the program knows where the if statement begins and ends.

In [25]:
print(5 < 3)
print(5==5)

if 5>0:
    print('5 is greater than 0')

False
True
5 is greater than 0


### For Loops

The last key ingredient of programming in any language is the for loop. It allows us to run a segment of code an arbitrary number of times (most of the time on different inputs). The power of this iterative way of approaching a problem is the often the reason we turn to a computer in the first place. The framework is as follows:

for x in X
do y to x

where x (scalar) is an element of X (a vector) and y does something to x

This will be much clearer with an example:

In [26]:
vector_3 = np.arange(5)
print(vector_3)

for i in 

SyntaxError: invalid syntax (<ipython-input-26-e0f930c68a5f>, line 4)

## Physics Recap

Before we continue, let's make sure we remember the Physics necessary to model radioactive decay. You will need a pencil/pen and paper for this bit.

* If we have N particles with each particle having a probability per second of decaying p, what is the rate of change of N (dN/dt)? 
* Why can't we simply integrate this equation (with respect to t)?
* Solve this differential equation to find N as a function of time. (Just look up the answer if you haven't studied any differential equations yet).
* Define the _half life_ of a radioactive sample.
* Derive the half life &lambda; using the equation for N found earlier.

There are answers and hints at the end of this document, but you should attempt this without them first.

## A Single Particle System